##Matrices

In [2]:
import numpy as np

In [3]:
np.random.seed(1)

np.random.randint (1,21, size=15)

array([ 6, 12, 13,  9, 10, 12,  6, 16,  1, 17,  2, 13,  8, 14,  7])

In [6]:
L = [i for i in np.random.randint (1,21, size=15) if i%2==0]
L

[6, 12, 10, 18, 14, 10, 10, 8]

In [7]:
L = [i for i in np.random.randint (1,21, size=40) if i%2==0]
L.sort()
L

[2,
 4,
 4,
 4,
 6,
 8,
 8,
 8,
 10,
 10,
 12,
 14,
 14,
 16,
 16,
 16,
 18,
 18,
 18,
 20,
 20,
 20]

In [13]:
L.pop(1)

4

In [16]:
L.remove(6)

In [10]:
L + [4]

[2, 4, 6, 8, 8, 8, 10, 10, 12, 14, 14, 16, 16, 16, 18, 18, 18, 20, 20, 20, 4]

In [26]:
L

[2, 8, 8, 10, 10, 12, 14, 14, 16, 16, 16, 18, 18, 18, 20, 20, 20]

In [53]:
L.pop(4)

16

In [54]:
L_arreglo =np.array(L)
L_arreglo

array([ 2,  8, 12, 16, 18, 18, 18, 20, 20])

In [55]:
len(L_arreglo)

9

In [60]:
L_matriz= L_arreglo.reshape(3,3)

In [59]:
M_matriz = np.array([2,3,14,19,13,0,25,6,9]).reshape(3,3)
M_matriz

array([[ 2,  3, 14],
       [19, 13,  0],
       [25,  6,  9]])

In [61]:
N= L_matriz @ M_matriz
N

array([[456, 182, 136],
       [824, 390, 386],
       [916, 434, 432]])

In [62]:
np.linalg.det(N)

51727.99999999955